name: Node.js CI 

on:
  push:
    branches: [ "tests-andy" ]  
  pull_request:
    branches: [ "tests-andy" ] 
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: .env
    strategy:
      matrix:
        node-version: [20.x]
        project: ["backend", "web-app", "mobile-app"]  

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies and run tests in ${{ matrix.project }}
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SECRET: ${{ secrets.SECRET }}
      run: |
        cd ${{ matrix.project }}
        npm ci
        npm run build --if-present
        npm test